#-------------------------------
# General Site Settings

title: MS Tours & Travels
description: MS Tours & Travels
email: budha.rocks@gmail.com

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Homepage for MS Tours & Travels'
  rel-author: 'https://github.com/Slackd'
  rel-publisher: 'https://github.com/Slackd'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#--------------
